---
shared:
  image: node:8
  steps:
    - init: |
        echo "Here we go."

jobs:
  dev-main-deploy:
    requires: [~sd@1006795:version-ecr-finish, ~commit]

  dev-main-deploy-combo-exclusive-start:
    requires: []

  dev-main-deploy-combo-exclusive:
    requires: [dev-main-deploy-combo-exclusive-start]

  dev-main-deploy-combo-non-combo-start:
    requires: []

  dev-main-deploy-non-combo:
    requires: [dev-main-deploy-combo-non-combo-start]

  dev-main-api:
    requires: [dev-main-deploy]

  dev-main-api-exclusive:
    requires: [dev-main-deploy-non-combo]

  dev-main-apicombo-exclusive:
    requires: [dev-main-deploy-combo-exclusive]

  dev-main-cleanup:
    requires: [~dev-main-deploy, ~dev-main-deploy-combo-exclusive, ~dev-main-deploy-non-combo]

  dev-main-delivery:
    requires: [~dev-main-deploy, ~dev-main-deploy-non-combo]

  dev-main-gdpr:
    requires: [~dev-main-deploy, ~dev-main-deploy-combo-exclusive, ~dev-main-deploy-non-combo]

  dev-main-finish:
    requires: [dev-main-api, dev-main-cleanup, dev-main-delivery, dev-main-gdpr]

  dev-main-combo-exclusive-finish:
    requires: [dev-main-apicombo-exclusive, dev-main-cleanup, dev-main-gdpr]

  dev-main-non-combo-finish:
    requires: [dev-main-api-exclusive, dev-main-cleanup, dev-main-delivery, dev-main-gdpr]
